language: cpp

git:
  depth: 5
  quiet: true

cache:
  directories:
    - External
    - KlayGE/media
    - KlayGE/Samples/media
    - KlayGE/Tests/media
    - KlayGE/Tools/media
    - KlayGE/Tutorials/media

matrix:
  include:
    - os: windows
      before_install:
        - choco install python3
      env: MATRIX_EVAL="CC=cl.exe && CXX=cl.exe" COMPILER="vc141"

    - os: windows
      before_install:
        - choco install python3
        - choco install mingw --version 7.3.0 --allow-downgrade
        # Workaround for CMake not wanting sh.exe on PATH for MinGW
        - export PATH=${PATH%:/c/Program Files/Git/usr/bin}
      env: MATRIX_EVAL="CC=gcc && CXX=g++" COMPILER="mingw"

    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - wine
            - wine-dev
            - winetricks
            - libx11-dev
            - libgl1-mesa-dev
            - libopenal-dev
          update:
            - true
      env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7" COMPILER="gcc"

    - os: linux
      dist: xenial
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - wine
            - wine-dev
            - winetricks
            - libx11-dev
            - libgl1-mesa-dev
            - libopenal-dev
          update:
            - true
      env: MATRIX_EVAL="CC=gcc-8 && CXX=g++-8" COMPILER="gcc"

    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - wine
            - wine-dev
            - winetricks
            - libx11-dev
            - libgl1-mesa-dev
            - libopenal-dev
          update:
            - true
      env: MATRIX_EVAL="CC=clang && CXX=clang++" COMPILER="clang"

    - os: linux
      dist: xenial
      sudo: required
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-7
          packages:
            - clang-7
            - libc++-7-dev
            - libc++abi-7-dev
            - wine
            - wine-dev
            - winetricks
            - libx11-dev
            - libgl1-mesa-dev
            - libopenal-dev
          update:
            - true
      env: MATRIX_EVAL="CC=clang-7 && CXX=clang++-7" COMPILER="clang"

    - os: osx
      osx_image: xcode9.4
      addons:
        homebrew:
          casks:
            - xquartz
          packages:
            - wine
          update:
            - true
      env: MATRIX_EVAL="CC=clang && CXX=clang++" COMPILER="clang"

    - os: osx
      osx_image: xcode10.1
      addons:
        homebrew:
          casks:
            - xquartz
          packages:
            - wine
          update:
            - true
      env: MATRIX_EVAL="CC=clang && CXX=clang++" COMPILER="clang" MACOSX_DEPLOYMENT_TARGET="10.14"

before_install:
  - eval "${MATRIX_EVAL}"
  # Linux
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export WINEARCH=win32;
      winetricks;
    fi

script:
  # Reset the repo to restore changes in External
  - git reset --hard
  - python BuildAll.py $COMPILER x64 Release
